Update CONTRIBUTING.md
gofair-foundation/fsr_qualification pull request #372
Opened 2023-11-28 21:42 UTC by mabablue

added git action to update issues and made some text edits to improve the guideline

2023-11-29 08:03 UTC, rbramley commented on CONTRIBUTING.md
> +6. In GitHub go to [GitHub/actions](https://github.com/gofair-foundation/fsr_qualification/actions): click on **issue_creation** and **run workflow** to update the issues with newly created FSR nanop
This should link to _Appendix B: Refreshing the GitHub issues list_ as that has a screenshot e.g. 
(See [Appendix B](#appendix-b-refreshing-the-github-issues-list))

Though does it belong in the one time set up steps?

2023-11-29 08:06 UTC, rbramley commented on CONTRIBUTING.md
> +9. Go back to your branch on GitHub and click on contribute: **Open pull request**
We can push commits to an existing PR for the branch (as described in step 8), so do not want to open a new Pull Request at this point.

2023-11-29 08:09 UTC, rbramley requested changes
The newly inserted step 9 (Line 217) is incorrect and needs to be removed.
Also, should the running of the action be in one time set up?

2023-11-30 19:12 UTC, mabablue commented on CONTRIBUTING.md
> +6. In GitHub go to [GitHub/actions](https://github.com/gofair-foundation/fsr_qualification/actions): click on **issue_creation** and **run workflow** to update the issues with newly created FSR nanop
no you are right. it should not be there...

2023-11-30 19:12 UTC, mabablue commented on CONTRIBUTING.md
> +9. Go back to your branch on GitHub and click on contribute: **Open pull request**
understood and agree

2023-12-01 10:16 UTC, rbramley reviewed
I've incorporated the wording changes into my latest branch with the images, so let's close this PR and delete the branch.

2023-12-01 10:16 UTC, rbramley commented on CONTRIBUTING.md
> +### **G1 A Setup steps (only needed once)**
This will break the anchor link - I've incorporated this change in a slightly different way on my latest branch.

2023-12-01 10:16 UTC, rbramley commented on CONTRIBUTING.md
> +10. **Merge pull request** and **confirm merge,** which closes the issue
This numbering is now out of sequence - I've incorporated the correction to the bold text on my latest branch.

2023-12-01 10:58 UTC, closed without merging